### ISSUE TITLE
Not Utilizing Image Size or Steps settings for Generations

### ISSUE THREAD

**Issue by NatureBeard** [thundaga/SD-webui-txt2img-script#10]
This may be because I have this script installed in the Vladomatic Automatic fork, but everything seems to work fine except even when I check the boxes for utilizing the Image settings for "steps", "cfg scale" & "size", it is using my settings/sliders in the UI and NOT from the image still.  I've ensured checkboxess are checked and restarted UI/service completely.

Happy to give any relevant info or work through this with someone to help find a fix.

Much appreciated!

**Comment by NatureBeard** [comment]
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/123671569/0aac2c92-b65a-46e4-9bda-22f340429592)
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/123671569/46a4cf6f-d770-4be1-a1d9-73fc4103f45a)

**Comment by NatureBeard** [comment]
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/123671569/c0d47e6a-41e4-4cb5-9afd-3e9500b0069b)

**Comment by thundaga** [comment]
Have you tried to see if this works on the vanilla sd webui, or does the issue still persist?

**Comment by OPCOXE** [comment]
Hi, you are using the Hires. fix with it (1st pic) can you verify without it ? 
I've check on the latest version and no issue, here is what I tested :

- Without Hires. fix
- With Hires. fix and defined output size (1080x1920)
- With Hires. fix and scaled output size (x2)

**Comment by NatureBeard** [comment]
Thank you for the responses. 

After reading these, restarts, further testing, and noticing that some images are bringing in settings in addition to prompts, and some are just bringing in the prompts, **It seems that my issues may be more related to specific image files that are missing** **some generation data somehow**. 

SOLUTION: Restarting seems to have fixed it from using the settings universally, except in odd cases where it doesn't pull from the images.

**The odd thing:** I have the settings on for .txt files of prompt, settings, and prompt template for easy viewing of prompts and improving my prompt editing process, and THOSE do show the steps/size/etc NOT being generated. 

This is maybe why having an additional option to run a folder with EITHER images OR the txt documents generated when settings for .txt files are set generally, and specifically for the Dynamic Prompts Plugin.

As this issue seems fixed generally on my end, beside odd one offs, I will close this issue. Thanks for the support.
