### ISSUE TITLE
Batch From Directory Fails if .txt Files exist

### ISSUE THREAD

**Issue by NatureBeard** [thundaga/SD-webui-txt2img-script#11]
Again, using the Vladomatic Fork on this, so perhaps this is the issue, but hoping to find a fix that allows me to use the batch processing of folders with Txt images with the prompt/generation info saved alongside the images. I get an error if the txt files are present along with.

Additionally, it would be really useful to have the option to process the folder as a batch and just use the txt files, OR the image files metadata.  Is this possible?

**Comment by thundaga** [comment]
1.  An error occurred since the folder is expected to only have images in them,  invalid images i.e images without metadata will be skipped.

2.  I have not added a text parsing feature for text files, out of curiosity though how are your text files with generation information organized/formatted.

3.  "process the folder as a batch" are you referring to inputting a series of folder directories to process generation info instead of the default single folder input/output UI option.

**Comment by NatureBeard** [comment]
Thanks for your response! I am utilizing the input folder as a path option.

I appreciated the skip invalid image feature! I noticed it only works for image files and not for txt.

I'm utilizing the "Create text file next to every image with generation parameters" setting in Automatic/Vladomatic which allows for creating .txt files next to each image matching the naming format of that generated image.

It includes almost all generation information/prompt/negative prompt/upscalers/steps/size/prompt template (if Dynamic prompts plugin is chosen and setting is enabled on the Dynamic Prompts tab) and more.

Here are the two ways it can show up in my output folders along with my images: 

1) Only enabling the main .txt file in settings ("Create text file next to every image with generation parameters") - This means only the prompt used (not dynamic prompt/wildcards/etc) to generate that one image.

> professional beautiful realistic ultra-HD ultra-3D photo of a Giant Elk looking pensive in a ultra detailed scene setting, photorealistic and lit with volumetric realistic ray traced lighting volumetric shadows volumetric texture volumetric depth and detail, ray tracing, realistic lighting, realistic shadows, realistic reflections, depth mapping, volumetric light and shadows, ultra-detailed, intricate detail, magic and gorgeous and professional portrait studio lighting, in the style of ultra-realistic multidimensional portal, blue and red color Theme, at dawn and during '70s
Negative prompt: title, name, caption, subtitle, text, words, label, signature, copyright, logo, scribble, deformed, disfigured, grotesque, gross, cut off, blurry, unfocused, watermark, fake, too many ears, too many fingers, too many legs, too many paws, angry, mean, bored, uneven eyes, grumpy, sad, snarl, blood, scary, aggressive, creepy, imperfect eyes, lopsided, uneven ears, asymmetrical face, imperfect face, ugly, deformity, red eyes, missing eyes, scary eyes, no eyes, lopsided eyes, frown, gun, weapon, violence, hurt, shoot, cannon, bomb, deformed hand, too many heads, double head, double face, bad face, too many arms, too many feet, too tall, stretched body, long legs, long neck, crooked eyes, crossed eyes, not anatomically correct, disproportion, monster, bizarre, amateur, disjointed, weak, ugly, poor composition, basic, simple, lacking details, simplistic, dull, lackluster, unimaginative, boring, campy, silly, trite
Steps: 394, Sampler: DPM++ SDE Karras, CFG scale: 4.0, Seed: 2016247982, Size: 832x480, Model hash: d88069cdb9, Model: .5(.85858RunDiffFX10.2DiffBrSWAIL++.15Delib+.15ProtogenNovaExp)+.5(Rundiff10), Denoising strength: 0.45, Clip skip: 1, Version: 6ea6f24, Token merging ratio: 0.5, Token merging ratio hr: 0.5, Parser: Full parser

2) Both the main .txt setting above AND Dynamic Prompts option for dynamic Templates used for that entire batch, regardless of wildcards/variables specifically used for that generation:

> professional majestic realistic ultra-HD ultra-3D photo of a perfect Cactus relaxing in a futuristic setting, photorealistic and lit with volumetric realistic ray traced lighting volumetric shadows volumetric texture volumetric depth and detail, ray tracing, realistic lighting, realistic shadows, realistic reflections, depth mapping, volumetric light and shadows, ultra-detailed, intricate detail, trending and professional portrait studio lighting and breathtaking, in the style of environmental photography, red and brown color Theme, in summer and during 2010s
Negative prompt: title, name, caption, subtitle, text, words, label, signature, copyright, logo, scribble, deformed, disfigured, grotesque, gross, ((low quality), ((normal quality)), ((bad quality)), amateur, homogeneous, sketch, cartoon, drawing, (anime:1.4), out of frame, worst quality, child, ((worst quality):1.5), (low quality:1.1), (normal quality:1.1), comic panel, scanlation, oversaturated, low contrast, underexposed, overexposed, compressed, noise, artifacts, jpeg artifacts, dithering, watermark, text, font, signage, collage, pixel, pixelated, bad quality, poor quality, out of frame, worst quality, digital illustration, disjointed, disfigured, messy, contortion, matte, soft focus, womanly, feminine, (low texture), (bad textures), (flat texture), ((unclear details)), (hazy details), (undefined features), bad rendering, 3d rendered, painting, digital painting, flat,
Steps: 246, Sampler: DPM++ SDE Karras, CFG scale: 8.0, Seed: 971653847, Size: 832x512, Model hash: ad1a10552b, Model: rundiffusionFX_v10, Denoising strength: 0.44, Clip skip: 1, Version: 6ea6f24, Token merging ratio: 0.5, Token merging ratio hr: 0.5, Parser: Full parser, Hires upscale: 2.5, Hires steps: 33, Hires upscaler: 4x-UltraSharp
Template: professional majestic realistic ultra-HD ultra-3D photo of a perfect Cactus relaxing in a futuristic setting, photorealistic and lit with volumetric realistic ray traced lighting volumetric shadows volumetric texture volumetric depth and detail, ray tracing, realistic lighting, realistic shadows, realistic reflections, depth mapping, volumetric light and shadows, ultra-detailed, intricate detail, trending and professional portrait studio lighting and breathtaking, in the style of environmental photography, red and brown color Theme, in summer and during 2010s
Negative Template: title, name, caption, subtitle, text, words, label, signature, copyright, logo, scribble, deformed, disfigured, grotesque, gross, ((low quality), ((normal quality)), ((bad quality)), amateur, homogeneous, sketch, cartoon, drawing, (anime:1.4), out of frame, worst quality, child, ((worst quality):1.5), (low quality:1.1), (normal quality:1.1), comic panel, scanlation, oversaturated, low contrast, underexposed, overexposed, compressed, noise, artifacts, jpeg artifacts, dithering, watermark, text, font, signage, collage, pixel, pixelated, bad quality, poor quality, out of frame, worst quality, digital illustration, disjointed, disfigured, messy, contortion, matte, soft focus, womanly, feminine, (low texture), (bad textures), (flat texture), ((unclear details)), (hazy details), (undefined features), bad rendering, 3d rendered, painting, digital painting, flat,, Postprocess upscale by: 2.8, Postprocess upscaler: 4x-UltraSharp

-----------------------------------------------

Having the option to choose if Image/text file/or Dynamic prompt is pulled into the generation info for wildcard/variable options to be included in the batching in this would be awesome.  Defaulting to the text document if it cannot read/does not have metadata in the matching image file would also be a great catchall. 

As it stands, I must copy all images I want to batch into a separate holding zone folder so the text documents do not cause an exception.

I understand that would require additional logic and parsing abilities to have the option to utilize text files, but I would be happy to help flesh out some code with GPT/copilot if anyone is up for helping me outline what would be required/what areas of the script would change/be added to, and what considerations/ logic would be required. 

If anyone could help me outline the areas that would change in this or are interested in working with me on adding this, I would really appreciate it for my workflow!

Thanks!

**Comment by thundaga** [comment]
Assuming that the text files are simply a copy of metadata already in the image files, I can put a skip for .txt extensions.
Just for clarification do both generations have duplicate information i.e the metadata in the image file is the same as the info in the text file next to it

**Comment by NatureBeard** [comment]
They do not have the same data as for the prompt template, which can have variables/wildcards present and produce a variety of prompts when utilized. 

I would be happy to mainly not have to delete txt files or move over copies of images, so the ability for it to skip the txt file unless data cannot be read from the image. 

My ultimate would be able to have folders of both images/text OR just folders of txt files like I have, to batch through the settings/prompt (or bonus: the template as an optional checkbox) would be amazing.

How feasible is this?

**Comment by thundaga** [comment]
Its possible, I'll have to look over  Vladomatic's repo to see how the outputs are to skip invalid txt files and use valid ones for prompt generations

**Comment by NatureBeard** [comment]
> Its possible, I'll have to look over Vladomatic's repo to see how the outputs are to skip invalid txt files and use valid ones for prompt generations

Please let me know if I can help somehow! Eager to learn or help

**Comment by thundaga** [comment]
yeah sure one way to parse this would be to recognize the delimiters(characters that separate the text information) within the text files in this case it would be the colons ":" and commas ",". then use them to find words before/after them and input them into a data structure and the value associated with it.
For example.
I recognize that the word "Steps" appears before a colon ":" and after a comma "," I'll take the word in between these delimiters and take the value after the colon ":" delimiter and identify what datatype the value is (string, int, float etc), for "Steps" its an int (integer) and then pass that data unto the image generation object.

Overall I think there might be a text parsing feature in the source code of the sd webui. I'll have to check that as well.
May take a little over a week till an update for this, but you can do some personal investigation if you'd like.
good luck 👍

**Comment by thundaga** [comment]
> They do not have the same data as for the prompt template, which can have variables/wildcards present and produce a variety of prompts when utilized.
> 
> I would be happy to mainly not have to delete txt files or move over copies of images, so the ability for it to skip the txt file unless data cannot be read from the image.
> 
> My ultimate would be able to have folders of both images/text OR just folders of txt files like I have, to batch through the settings/prompt (or bonus: the template as an optional checkbox) would be amazing.
> 
> How feasible is this?

I updated the repository, you should now be able to parse info from the text files.
Just to note, if both the metadata is in the image and text next to it, you will get duplicates, so just make sure that only the "Create a text file next to every image with generation parameters." setting is checked instead of the setting above it which is "Save text information about generation parameters as chunks to png files" .

When you have the time let me know if it works on your end.
