### ISSUE TITLE
How to set default values for the checkboxes?

### ISSUE THREAD

**Issue by spryroX** [thundaga/SD-webui-txt2img-script#12]
In the older versions it was possible to set defaults for the checkboxes via ui-config.json
Recently the checkboxes have been changes to CheckBoxGroup and it seems it's no longer possible to set defaults.
Is there a way I can still set defaults so I don't have to enable all the checkboxes every time I want to use the script?

Thanks for the script!

**Comment by spryroX** [comment]
Just for reference, this is how I had it set up on previous versions through ui-config.json
```
    "customscript/process_png_metadata.py/txt2img/Input directory/visible": true,
    "customscript/process_png_metadata.py/txt2img/Input directory/value": "",
    "customscript/process_png_metadata.py/txt2img/Output directory/visible": true,
    "customscript/process_png_metadata.py/txt2img/Output directory/value": "",
    "customscript/process_png_metadata.py/txt2img/Assign Prompt/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Prompt/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Negative Prompt/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Negative Prompt/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Seed/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Seed/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Sampler Name/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Sampler Name/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Steps/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Steps/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign CFG scale/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign CFG scale/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Width and Height/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Width and Height/value": true,
    "customscript/process_png_metadata.py/txt2img/Assign Denoising strength/visible": true,
    "customscript/process_png_metadata.py/txt2img/Assign Denoising strength/value": false,
    "customscript/process_png_metadata.py/txt2img/Tags to add at the front/visible": true,
    "customscript/process_png_metadata.py/txt2img/Tags to add at the front/value": "",
    "customscript/process_png_metadata.py/txt2img/Tags to add at the end/visible": true,
    "customscript/process_png_metadata.py/txt2img/Tags to add at the end/value": "",
    "customscript/process_png_metadata.py/txt2img/Tags to remove/visible": true,
    "customscript/process_png_metadata.py/txt2img/Tags to remove/value": "",
```
In the new version we only have these:
```
    "customscript/process_png_metadata_v2.py/txt2img/Input directory/visible": true,
    "customscript/process_png_metadata_v2.py/txt2img/Input directory/value": "",
    "customscript/process_png_metadata_v2.py/txt2img/Output directory/visible": true,
    "customscript/process_png_metadata_v2.py/txt2img/Output directory/value": "",
    "customscript/process_png_metadata_v2.py/txt2img/Tags to add at the front/visible": true,
    "customscript/process_png_metadata_v2.py/txt2img/Tags to add at the front/value": "",
    "customscript/process_png_metadata_v2.py/txt2img/Tags to add at the end/visible": true,
    "customscript/process_png_metadata_v2.py/txt2img/Tags to add at the end/value": "",
    "customscript/process_png_metadata_v2.py/txt2img/Tags to remove/visible": true,
    "customscript/process_png_metadata_v2.py/txt2img/Tags to remove/value": ""
```

Having to set it from the script itself or config doesn't really matter to me. I've tried to hack into the script myself but couldn't figure out how to do it even with using the gradio docs. Thanks for looking into it!

**Comment by OPCOXE** [comment]
For the hardcoded version with the script, you can simply add value = ["Checkpoint"] at the end of the creation function like this :

options = gr.CheckboxGroup(choices = ["Checkpoint", "Prompt", "Negative Prompt", "Seed", "Variation Seed", "Variation Seed Strenght", "Sampler", "Steps", "CFG scale", "Width and Height", "Upscaler", "Denoising Strength", "Hires Scale or Width and Height", "Clip Skip", "Face restoration"], label="Assign from input image 2", info="Checked : Assigned from the input images\nUnchecked : Assigned from the UI", value = ["Checkpoint"])

If you need more you can put more like explain in my previous message.
For the config-ui, I'm working on it but it seems not related to the script since all settings are in the file exept the CheckboxGroup. We can get back to Checkboxes but I don't think it's the best idea, I'm still searching for info and testing

**Comment by OPCOXE** [comment]
I just verified and the issue come from the webui itself, it doesn't store nor load CheckboxGroups.
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/94632173/7b18e3f9-2152-4463-bb52-acec3db811e9)
I'll continue to test some things that I have in mind but I'm not sure to find a good solution

**Comment by OPCOXE** [comment]
Quick fix with dropdown menu is to replace the line 153 by this :
options = gr.Dropdown(list(prompt_options.keys()), label="Assign from input image", info="Select are assigned from the input, the rest from UI", multiselect = True)
Nothing else to do, when launching the webui a field will be created inside the ui-config.json and you can put the value in there (Same format as for the CheckboxGroup : ["Checkpoint", "Seed"])

**Comment by OPCOXE** [comment]
And I'll provide a pull request to change it.
[thundaga](https://github.com/thundaga) will choose to accept it or not, honestly I was stupid to not go for this and go for the CheckboxGroup but I didn't know and didn't searched enough. For me it feels better to use this so it should be ok

**Comment by NatureBeard** [comment]
Not sure if Automatic1111 has this, but Vladomatic branch has a default UI settings tab to enable/reset/save to ensure all of your basic/latest/current desired next settings and checkboxes are there.

Does not work for EVERYTHING, but most of the XYX I utilize. It does NOT remember XYZ Model lists... must be due to order of list loading vs this plugin.

**Comment by spryroX** [comment]
> 

Tested the changes and it's working great. Going by what you said earlier it sounds more like a bug in Automatic1111, but this is a nice workaround. 

Thanks again, this script is very useful.
