### ISSUE TITLE
The scripts do not show up after putting the py file in the scripts folder.

### ISSUE THREAD

**Issue by StellineOrb** [thundaga/SD-webui-txt2img-script#15]
The scripts do not show up after putting the py file in the scripts folder. Tried several different versions of SD. Same result here.

**Comment by thundaga** [comment]
Just pulled in the most recent version of the web ui, "Process Png Metadata Info" still pops up.
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/54699968/555f044d-8c06-42ee-9f2c-abbc9700729f)

By any chance is this the only script not showing up?
What does the console log show relating to the script?
Only error I see is:
`stable-diffusion-webui\scripts\process_png_metadata.py:142: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.   with gr.Row().style(equal_height=False, variant='compact'):`
But that's just a warning for legacy code.

**Comment by StellineOrb** [comment]
![微信图片_20231126041247](https://github.com/thundaga/SD-webui-txt2img-script/assets/148488922/be828107-b461-4dad-9f58-6dd60aac0c93)
![微信图片_20231126041221](https://github.com/thundaga/SD-webui-txt2img-script/assets/148488922/d00ab8ef-43c9-4954-9fb4-88dc2a7c198e)
Pls see my script list and extension list. Any possible conflict?
I use a popular mega pack but I also tried clean SD versions. It is weird. Pls let me know what info is needed so you can help me solve this issue. I process a lot of images and your script may help to increase my efficiency a lot. Thank you.

**Comment by StellineOrb** [comment]
Also, one script in Chinese is "load prompt from textbox or file". But it does not help me much actually. Maybe this one has a conflict? I tried to disable all the extensions but no good. I did not try to remove other scripts.

**Comment by StellineOrb** [comment]
![微信图片_20231126065022](https://github.com/thundaga/SD-webui-txt2img-script/assets/148488922/3c18de31-dab2-4d38-bf5b-bafcb7d0f45e)
I see the scripts error, pls check.

**Comment by thundaga** [comment]
@StellineOrb is there more to this traceback?

**Comment by StellineOrb** [comment]
![微信图片_20231126071754](https://github.com/thundaga/SD-webui-txt2img-script/assets/148488922/4d9f200c-d59f-4a85-a30c-98d2eacfb58e)
Sorry, I did not send the full traceback.

**Comment by thundaga** [comment]
@staline can you upload the script file?

**Comment by StellineOrb** [comment]
[process_png_metadata.zip](https://github.com/thundaga/SD-webui-txt2img-script/files/13466727/process_png_metadata.zip)
This one is just downloaded 1 hour ago from here.

**Comment by thundaga** [comment]
Your file size is much bigger than expected 
![image](https://github.com/thundaga/SD-webui-txt2img-script/assets/54699968/525598ee-3b05-431f-91c9-117a9d160479)

can you just show me a screenshot of what's going on around line 95 in the script
Based on the traceback there is not supposed to be anything on that line so it may just need an invalid character removed.

**Comment by StellineOrb** [comment]
I realized what actually happened. I right-clicked the file and saved directly, while it is the webpage. Now I copy the code and post it directly in a py file, it shows up. Totally my bad. Thanks for your quick reply and time. Will let you know if there are any issues when using it. Your script will save my life. I process a lot of images with random prompts every day... i2i is not as good as high-res fix.
