### ISSUE TITLE
CFG scale issue: int to float

### ISSUE THREAD

**Issue by add63sugar** [thundaga/SD-webui-txt2img-script#2]
Hi!

Today I try to use some other script, it will generate CFG scale:"7.0" instead of "7"
It cause ERROR when running your script, the below line150, I need to change from int to float, now it is running smoothly.
But for line 149, seems it should be 'CFG scale' instead of 'Seed'? Not sure it affects the script or not.

line149            if options.cfg_scale and 'Seed' in parsed_text:        
line150                p.cfg_scale = int(parsed_text['CFG scale'])        

Thanks!!

**Comment by thundaga** [comment]
Changed the data type conversion, strange I didn't see that, repos been updated for the cfg scale parsing
