### ISSUE TITLE
Doesn't work or can't be found.

### ISSUE THREAD

**Issue by Ozanta** [thundaga/SD-webui-txt2img-script#3]
I apologize if I'm doing something wrong, but where exactly is this script located? In which tab? Maybe it stopped working in the new version?

**Comment by thundaga** [comment]
There is a "scripts" Folder in the "stable diffusion webui" folder. 
Download the "process_png_metadata.py" file from the git repository "https://github.com/thundaga/SD-webui-txt2img-script".
Move that python file into the scripts folder then reload the webui.
The script titled "Process PNG Metadata Info" should be under the "scripts" section for the txt2img tab.
good luck and let me know if this helps 👍

**Comment by Ozanta** [comment]
Thank you, it works.
I tried to install the script through the link on the extensions page. I think you should add in the description that you should only install manually.
Once again, I apologize.
